### ISSUE TITLE
bad pre-task

### ISSUE THREAD

**Issue by frank3427** [YanChii/ansible-role-postgres-ha#2]
centos 7 does not install iptables it uses firewalld
the following does not work;
      pre_tasks:
        - name: disable firewall
          service: name=iptables state=stopped enabled=no

**Comment by YanChii** [comment]
Hi @frank3427 

this pre_task is only the example. You should not disable system firewall (either iptables or firewalld) on the production system.
I recommend adding some firewall role before the `postgres-ha` role.

But you are right, the example should have `firewalld` as a service name. I'll change that.

Thanks
Jan

**Comment by YanChii** [comment]
Changed. If you see any other inconsistencies, please let me know.
Jan
