### ISSUE TITLE
postgres_ha_paf_geo_patch no longer needed after PAF v2.2.1 release

### ISSUE THREAD

**Issue by tamer-hassan** [YanChii/ansible-role-postgres-ha#24]
Thanks @YanChii , your patch was incorporated in the latest release PAF v2.2.1
https://github.com/ClusterLabs/PAF/releases/tag/v2.2.1

So maybe it would be helpful or less confusing to remove it now?

**Comment by YanChii** [comment]
Hi @Tamer,

Thank you for letting me know. I'll update the role to use the newest release.

But you are only partly right.

This patch is not needed anymore:
https://github.com/YanChii/ansible-role-postgres-ha/blob/master/tasks/paf.yml#L26

But the GEO patch itself is not incorporated in the upstream and is still needed if you want to run pg cluster without fencing:
https://github.com/YanChii/ansible-role-postgres-ha/blob/master/tasks/paf.yml#L37

Jan

**Comment by tamer-hassan** [comment]
@YanChii You're absolutely correct.
I couldn't wait, and the changes to the pgsqlms were minimal between 2.2.0 - 2.2.1, including some that were already applied by your patch, so I easily merged the changes.
Attached the patched pgsqlms in case someone is impatient (or on a deadline) like me :)
p.s. I only renamed and appended file extension ".txt" to appease github's file type checking on upload.
[pgsqlms-2.2.1-geo-patched.txt](https://github.com/YanChii/ansible-role-postgres-ha/files/2856128/pgsqlms-2.2.1-geo-patched.txt)

**Comment by YanChii** [comment]
Hi Tamer,
thank you for your patch. I'll commit the updated version right away.
Jan
