### ISSUE TITLE
Parameterize the interval?

### ISSUE THREAD

**Issue by ioguix** [YanChii/ansible-role-postgres-ha#6]
Hi,

Reading at my colleague PR #4, I discovered the monitor intervals where fixed to 15 and 16s. I suppose it would be nice to be able to set them to different values based on the cluster requirement.

https://github.com/YanChii/ansible-role-postgres-ha/blob/a3ea651544a507b44ee2d94e33d649502a157254/tasks/paf.yml#L60

Thoughts?

**Comment by YanChii** [comment]
Hi.

No problem, it can be easily parametrized.
Parametrizing of these parameters makes sense to me:
`monitor_interval_master`
`monitor_interval_slave`

And maybe also a check that these two parameters are not set to the same value.

I'll take a look at it.

Jan

**Comment by ioguix** [comment]
> And maybe also a check that these two parameters are not set to the same value.

+1, mandatory :)
